I'm sorry, but an uncaught exception occurred.

While running game code:
TypeError: unbound method get_tooltip() must be called with Quit instance as first argument (got nothing instead)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "/Applications/renpy-6.99.14.3-sdk/renpy/ast.py", line 912, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-6.99.14.3-sdk/renpy/python.py", line 2004, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
    python hide:
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
    ui.interact()
  File "/Applications/renpy-6.99.14.3-sdk/renpy/ui.py", line 295, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Applications/renpy-6.99.14.3-sdk/renpy/display/core.py", line 2699, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/Applications/renpy-6.99.14.3-sdk/renpy/display/core.py", line 3507, in interact_core
    rv = renpy.display.focus.mouse_handler(ev, x, y)
  File "/Applications/renpy-6.99.14.3-sdk/renpy/display/focus.py", line 407, in mouse_handler
    return change_focus(new_focus, default=default)
  File "/Applications/renpy-6.99.14.3-sdk/renpy/display/focus.py", line 362, in change_focus
    set_focused(current, newfocus.arg, newfocus.screen)
  File "/Applications/renpy-6.99.14.3-sdk/renpy/display/focus.py", line 109, in set_focused
    new_tooltip = widget._get_tooltip()
  File "/Applications/renpy-6.99.14.3-sdk/renpy/display/behavior.py", line 746, in _get_tooltip
    return get_tooltip(self.action)
  File "/Applications/renpy-6.99.14.3-sdk/renpy/display/behavior.py", line 373, in get_tooltip
    return func()
TypeError: unbound method get_tooltip() must be called with Quit instance as first argument (got nothing instead)

Darwin-16.6.0-x86_64-i386-64bit
Ren'Py 7.3.2.320
Hurricane Like Me Renpy 7.2.2.491
Sun Aug 25 11:56:47 2019
